<?php
class ProfitAndLoss {
        public $settings = array(
                'name' => 'Profit And Loss',
                'admin_menu_category' => 'Accounting',
                'admin_menu_name' => 'Profit And Loss',
                'admin_menu_icon' => '<i class="icon-legal"></i>',
                'description' => 'Generates a Profit and Loss report. Warning: The Author and billic take no responsibility and/or liability for the accuracy of the report generated by this tool.',
        );
        function admin_area() {
                global $billic, $db;
                $billic->set_title('Admin/Profit and Loss');
                if (empty($_POST['date_start']) || empty($_POST['date_end'])) {
                        echo '<h1><i class="icon-legal"></i> Profit and Loss</h1>';
                        echo '<link rel="stylesheet" href="/i/js/jquery-ui.css" /><script src="/i/js/jquery-ui.js"></script>';
                        echo '<form method="POST">';
                        echo '<table class="table table-striped" style="width: 300px;"><tr><th colspan="2">Generate</th></tr>';
                        echo '<tr><td>Start Date</td><td><input type="text" class="form-control" name="date_start" id="date_start" value="' . date('Y') . '-01-01" class="form-control"></td></tr>';
                        echo '<tr><td>End Date</td><td><input type="text" class="form-control" name="date_end" id="date_end" value="' . date('Y') . '-12-' . date('t', mktime(0, 0, 0, 12, 1, date('Y'))) . '" class="form-control"></td></tr>';
                        echo '<tr><td colspan="2" align="right"><input type="submit" class="btn btn-default" name="generate" value="Generate &raquo" class="btn btn-success"></td></tr>';
                        echo '</table>';
                        echo '<script>
                        $(function() {
                                $( "#date_start" ).datepicker({
                                        dateFormat: "yy-mm-dd"
                                });
                                $( "#date_end" ).datepicker({
                                        dateFormat: "yy-mm-dd"
                                });
                        });
                        </script>';
                        echo '</form>';
                        exit;
                }
                $date = date_create_from_format('Y-m-d', $_POST['date_start']);
                $date->setTime(0, 0, 0);
                $date_start = $date->getTimestamp();
                $date = date_create_from_format('Y-m-d', $_POST['date_end']);
                $date->setTime(0, 0, 0);
                $date_end = ($date->getTimestamp() + 86399);
                echo '<h1><i class="icon-legal"></i> Profit and Loss Statement from ' . date('Y-m-d', $date_start) . ' to ' . date('Y-m-d', $date_end) . '</h1>';
                echo '<table class="table table-striped">';
                echo '<tr><th>Income</th><th align="center">' . get_config('billic_currency_code') . '</th><th align="center">' . get_config('billic_currency_code') . '</th></tr>';
                $invoices = $db->q('SELECT * FROM `invoices` WHERE `date` >= ? AND `date` <= ? AND `status` = ?', $date_start, $date_end, 'Paid');
                $sales = 0;
                $total_credit = 0;
                foreach ($invoices as $invoice) {
                        $total_credit += $invoice['credit'];
                        $invoice_total = ($invoice['subtotal'] - $invoice['credit']);
                        if ($invoice_total<0)
                                echo "Warning: Total for Invoice #{$invoice['id']} is less than zero ($invoice_total)!<br>";
                        $sales+= $invoice_total;
                }
                echo '<tr><td>Sales</td><td style="border-bottom:1px solid red">' . number_format($sales, 2) . '</td><td></td></tr>';
                echo '<tr><td>Credit Notes</td><td style="border-bottom:1px solid red">(' . number_format($total_credit, 2) . ')</td><td></td></tr>';
                echo '<tr><td>Total Income</td><td></td><td>' . number_format($sales-$total_credit, 2) . '</td></tr>';
                echo '<tr><th colspan="2">Operating Expenses</th></tr>';
                $transactions = $db->q('SELECT * FROM `transactions` WHERE `amount` < 0 AND `date` >= ? AND `date` <= ?', $date_start, $date_end);
                $expenses = array();
                foreach ($transactions as $transaction) {
                        if (stripos($transaction['description'], 'refund') !== false) {
                                //$transaction['description'] = 'Refund';
                                continue;
                        }
                        $expenses[$transaction['description']]+= abs($transaction['amount']);
                }
                $i = 1;
                $total_expenses = 0;
                foreach ($expenses as $description => $total) {
                        $total_expenses+= $total;
                        echo '<tr><td>' . $description . '</td><td' . ($i == count($expenses) ? ' style="border-bottom:1px solid red"' : '') . '>' . number_format($total, 2) . '</td></tr>';
                        $i++;
                }
                echo '<tr><td>Total Operating Expenses</td><td></td><td style="border-bottom:1px solid red">' . number_format($total_expenses, 2) . '</td></tr>';
                $gross_profit = ($sales - $total_expenses);
                echo '<tr><td>Gross Profit before Tax</td><td></td><td style="border-bottom:1px double red">' . number_format($gross_profit, 2) . '</td></tr>';
                echo '</table><br>';
        }
}
